import "./globals.css";
import Head from "next/head";

export const metadata = {
  title: "Viva-La-Pizza",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        
        <link href="https://fonts.cdnfonts.com/css/beyond-the-mountains" rel="stylesheet"></link>
      </Head>
      <body className="font-open-sans">
        {children}
      </body>
    </html>
  );
}
